export const ADVERT_CREATED_REQUEST = 'ADVERTS_CREATED_REQUEST';
export const ADVERT_CREATED_SUCCESS = 'ADVERTS_CREATED_SUCCESS';
export const ADVERT_CREATED_FAILURE = 'ADVERTS_CREATED_FAILURE';

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'ADVERTS_LOADED_FAILURE';

export const ADVERT_DELETED_REQUEST = 'ADVERTS_DELETED_REQUEST';
export const ADVERT_DELETED_SUCCESS = 'ADVERTS_DELETED_SUCCESS';
export const ADVERT_DELETED_FAILURE = 'ADVERTS_DELETED_FAILURE';

export const ADVERT_DETAIL_REQUEST = 'ADVERT_DETAIL_REQUEST';
export const ADVERT_DETAIL_SUCCESS = 'ADVERT_DETAIL_SUCCESS';
export const ADVERT_DETAIL_FAILURE = 'ADVERT_DETAIL_FAILURE';

export const ADVERT_EDIT_REQUEST = 'ADVERTS_EDIT_REQUEST';
export const ADVERT_EDIT_SUCCESS = 'ADVERTS_EDIT_SUCCESS';
export const ADVERT_EDIT_FAILURE = 'ADVERTS_EDIT_FAILURE';

export const AUTH_LOGGED = 'AUTH_LOGGED';
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
export const UI_RESET_ERROR = 'UI_RESET_ERROR';

export const TAGS_LOADED_REQUEST = 'TAGS_LOADED_REQUEST';
export const TAGS_LOADED_SUCCESS = 'TAGS_LOADED_SUCCESS';
export const TAGS_LOADED_FAILURE = 'TAGS_LOADED_FAILURE';

export const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
export const AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_FORGOT_PASSWORD_SUCCESS';
export const AUTH_FORGOT_PASSWORD_FAILURE = 'AUTH_FORGOT_PASSWORD_FAILURE';

export const AUTH_NEW_PASSWORD_REQUEST = 'AUTH_NEW_PASSWORD_REQUEST';
export const AUTH_NEW_PASSWORD_SUCCESS = 'AUTH_NEW_PASSWORD_SUCCESS';
export const AUTH_NEW_PASSWORD_FAILURE = 'AUTH_NEW_PASSWORD_FAILURE';

export const USER_LOGGED_SUCCESS = 'USER_LOGGED_SUCCESS';
export const USER_LOGGED_REQUEST = 'USER_LOGGED_REQUEST';
export const USER_LOGGED_FAILURE = 'USER_LOGGED_FAILURE';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';
